[package]
name = "mr-prober"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio"] }
enclose = { version = "1" }
